# Generated by Django 3.0.4 on 2020-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_todo_vung_bachmai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='tep download moi nhat', max_length=30)),
                ('specifications', models.FileField(default='', upload_to='upload')),
            ],
            options={
                'verbose_name_plural': 'Upload tệp ',
            },
        ),
    ]
