# Generated by Django 3.0.4 on 2020-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_router'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='router',
            options={'verbose_name_plural': 'Văn bản chỉ đạo'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='vung_bachmai',
            new_name='yeutodichte',
        ),
        migrations.AlterField(
            model_name='router',
            name='specifications',
            field=models.FileField(default='', upload_to='upload', verbose_name='Upload'),
        ),
        migrations.AlterField(
            model_name='router',
            name='title',
            field=models.CharField(default='Văn bản chỉ đạo', max_length=150, verbose_name='tiêu đề'),
        ),
    ]
